openapi: 3.0.3
info:
  title: Klink API
  version: 1.3.0
  description: |-
    API for administrasjon av dokumentarkiver med passordbeskyttelse og lenkestruktur.
    Hvert arkiv må ha en eier (e-post).
    Serveren kan sikres med et globalt 'X-Server-Token'.
    Sett miljøvariabel KLINKPORT for alternativ portnummer.
servers:
  - url: http://localhost:54827

components:
  securitySchemes:
    ArchiveAuth:
      type: apiKey
      in: header
      name: Archive
    PasswordAuth:
      type: apiKey
      in: header
      name: Password
    ServerTokenAuth:
      type: apiKey
      in: header
      name: X-Server-Token

  schemas:
    ArchiveInfo:
      type: object
      properties:
        name:
          type: string
          description: Navnet på arkivet.
        owner:
          type: string
          format: email
          description: E-postadressen til eieren av arkivet.
    Document:
      type: object
      properties:
        name:
          type: string
          description: Dokumentets navn (f.eks. 'dokument.kli').
        path:
          type: string
          description: Dokumentets sti (f.eks. 'mappe/undermappe').
        body:
          type: string
          description: Innholdet i dokumentet.
        lastupdated:
          type: string
          format: date-time
        updatedby:
          type: string
        timestamp:
          type: string
          format: date-time
        incominglinks:
          type: string
          description: En kommaseparert liste med dokumenter som lenker til dette.
    DocumentRequest:
      type: object
      required:
        - name
        - body
      properties:
        name:
          type: string
        path:
          type: string
        body:
          type: string
    DeleteDocumentRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        path:
          type: string
    RenameDocumentRequest:
      type: object
      required:
        - oldFullname
        - newFullname
      properties:
        oldFullname:
          type: string
          description: Det fulle navnet på dokumentet som skal endres (inkl. sti og .kli).
        newFullname:
          type: string
          description: Det nye fulle navnet på dokumentet (inkl. sti og .kli).

# Global sikkerhet som gjelder for alle endepunkter med mindre de overstyrer det lokalt.
security:
  - ArchiveAuth: []
    PasswordAuth: []
    ServerTokenAuth: []

paths:
  /set_server_token:
    post:
      summary: Sett server-token (engangsoperasjon)
      description: Setter det globale server-tokenet. Kan bare kjøres én gang, når tokenet er tomt.
      responses:
        '200':
          description: Server-token ble satt.
        '400':
          description: Manglende X-Server-Token header.
        '409':
          description: Server-token er allerede satt og kan ikke endres.
      security:
        - ServerTokenAuth: [] # Krever kun token for å sette seg selv

  /list_archives:
    get:
      summary: List alle tilgjengelige arkiver med eiere
      description: Returnerer en liste over alle arkiver med tilhørende eier. Krever ingen autentisering.
      responses:
        '200':
          description: En liste med arkiv-objekter (navn og eier).
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArchiveInfo'
        '500':
          description: Intern serverfeil ved henting av arkiver.
      security: [] # Ingen sikkerhet, dette er et offentlig endepunkt.

  /create_archive:
    post:
      summary: Opprett nytt arkiv med en eier
      parameters:
        - in: header
          name: Owner-Email
          required: true
          schema:
            type: string
            format: email
          description: En gyldig e-postadresse for arkivets eier.
      responses:
        '200':
          description: Arkiv opprettet.
        '400':
          description: Manglende eller ugyldig header (Archive, Password, eller Owner-Email).
        '401':
          description: Uautorisert. Manglende eller ugyldig server-token.
        '409':
          description: Et arkiv med dette navnet finnes allerede.

  /documents:
    get:
      summary: List alle dokumenter i arkivet
      parameters:
        - in: query
          name: sincetimestamp
          required: false
          schema:
            type: string
            format: date-time
          description: Valgfritt. Returnerer kun dokumenter hvor 'lastupdated' er nyere enn dette tidspunktet (minus 3 sek). Bruker ISO 8601 format.
      responses:
        '200':
          description: Liste av dokumenter. Kan være filtrert.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
        '400':
          description: Ugyldig format på 'sincetimestamp'.
        '401':
          description: Uautorisert. Manglende eller ugyldig server-token.
        '403':
          description: Feil arkiv/passord.

  /rename_document:
    post:
      summary: Gi et dokument et nytt navn
      description: Endrer navnet på et dokument og oppdaterer alle referanser til det i databasen.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RenameDocumentRequest'
      responses:
        '200':
          description: Navneendring var vellykket.
        '400':
          description: Ugyldig input i request body.
        '401':
          description: Uautorisert. Manglende eller ugyldig server-token.
        '403':
          description: Feil arkiv/passord.
        '404':
          description: Dokumentet som skulle endres ble ikke funnet.
        '409':
          description: Det nye dokumentnavnet er allerede i bruk.
        '500':
          description: En intern feil oppsto. Transaksjonen ble rullet tilbake.

  /insert:
    post:
      summary: Sett inn eller oppdater et dokument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentRequest'
      responses:
        '200':
          description: Dokument opprettet/oppdatert
        '400':
          description: Ugyldig input
        '401':
          description: Uautorisert. Manglende eller ugyldig server-token.
        '403':
          description: Feil arkiv/passord

  /retrieve:
    get:
      summary: Hent et dokument med full path
      parameters:
        - in: query
          name: fullname
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Dokumentdata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '400':
          description: Manglende parametere
        '401':
          description: Uautorisert. Manglende eller ugyldig server-token.
        '403':
          description: Feil arkiv/passord
        '404':
          description: Dokument ikke funnet

  /delete_document:
    delete:
      summary: Slett et dokument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteDocumentRequest'
      responses:
        '200':
          description: Sletting utført
        '400':
          description: Ugyldig input
        '401':
          description: Uautorisert. Manglende eller ugyldig server-token.
        '403':
          description: Feil arkiv/passord